exports.SAVED = 'your wish is my command'
exports.TRY_AGAIN = 'uhh..try again'
exports.STYLES_PACK = 'tradle.StylesPack'
exports.INTRODUCTION = 'Ahh, finally, someone fashion conscious! Type "help" to see what I can do'
exports.NO_COMPRENDO = 'I don\'t understand. If you\'re lost or a total noob, type "help"'
exports.WHOA_GENIUS = 'Whoa! Are you some kind of chat UI feng shui genius?'
